@startuml

start
split
    :load existing from CSV;
split again
    :load new from web;
end split
:update existing with new;
:write updated to CSV;
split
    :transform to big format;
    :export;
split again
    :transform to small format;
    :export;
end split
end

start
:load from web/cache;
:append translation;
:create cards;
:write cards;
end

@enduml